/**
 * AutomartLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreatePurchaseOrderRequest
 */
class CreatePurchaseOrderRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.buyerId = this.constructor.getValue(obj.buyerId);
        this.carId = this.constructor.getValue(obj.carId);
        this.amount = this.constructor.getValue(obj.amount);
        this.status = this.constructor.getValue(obj.status);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'buyerId', realName: 'buyerId' },
            { name: 'carId', realName: 'carId' },
            { name: 'amount', realName: 'amount' },
            { name: 'status', realName: 'status' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreatePurchaseOrderRequest;
