/**
 * AutomartLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const LoginRequest = require('../lib/Models/LoginRequest');
const CreatePurchaseOrderRequest = require('../lib/Models/CreatePurchaseOrderRequest');
const UpdateThePriceOfACarAdRequest = require('../lib/Models/UpdateThePriceOfACarAdRequest');
const UpdatePriceOfAPurchaseOrderRequest =
  require('../lib/Models/UpdatePriceOfAPurchaseOrderRequest');
const MarkPostedAdAsSoldRequest = require('../lib/Models/MarkPostedAdAsSoldRequest');
const SignupRequest = require('../lib/Models/SignupRequest');
const PostAdRequest = require('../lib/Models/PostAdRequest');
const FlagAPostedCarAdRequest = require('../lib/Models/FlagAPostedCarAdRequest');

const classMap = {
    LoginRequest,
    CreatePurchaseOrderRequest,
    UpdateThePriceOfACarAdRequest,
    UpdatePriceOfAPurchaseOrderRequest,
    MarkPostedAdAsSoldRequest,
    SignupRequest,
    PostAdRequest,
    FlagAPostedCarAdRequest,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
